from ....const import API_PATH as API_PATH

class GildableMixin:
    def award(self, *, gild_type: str = ..., is_anonymous: bool = ..., message: str = ...) -> dict: ...
    def gild(self) -> dict: ...
