from ...util import cachedproperty as cachedproperty
from ..base import PRAWBase as PRAWBase
from typing import Any, Optional

class PollOption(PRAWBase): ...

class PollData(PRAWBase):
    def user_selection(self) -> Optional[PollOption]: ...
    def __setattr__(self, attribute: str, value: Any): ...
    def option(self, option_id: str) -> PollOption: ...
