import praw
from ...const import API_PATH as API_PATH, JPEG_HEADER as JPEG_HEADER
from ...exceptions import ClientException as ClientException, InvalidFlairTemplateID as InvalidFlairTemplateID, MediaPostFailed as MediaPostFailed, RedditAPIException as RedditAPIException, TooLargeMediaException as TooLargeMediaException, WebSocketException as WebSocketException
from ...util import cachedproperty as cachedproperty
from ..listing.generator import ListingGenerator as ListingGenerator
from ..listing.mixins import SubredditListingMixin as SubredditListingMixin
from ..util import permissions_string as permissions_string, stream_generator as stream_generator
from .base import RedditBase as RedditBase
from .emoji import SubredditEmoji as SubredditEmoji
from .mixins import FullnameMixin as FullnameMixin, MessageableMixin as MessageableMixin
from .modmail import ModmailConversation as ModmailConversation
from .removal_reasons import SubredditRemovalReasons as SubredditRemovalReasons
from .rules import SubredditRules as SubredditRules
from .widgets import SubredditWidgets as SubredditWidgets, WidgetEncoder as WidgetEncoder
from .wikipage import WikiPage as WikiPage
from _typeshed import Incomplete
from requests import Response as Response
from typing import Any, Dict, Generator, Iterator, List, Optional, Union

class Subreddit(MessageableMixin, SubredditListingMixin, FullnameMixin, RedditBase):
    STR_FIELD: str
    MESSAGE_PREFIX: str
    @property
    def banned(self) -> praw.models.reddit.subreddit.SubredditRelationship: ...
    @property
    def collections(self) -> praw.models.reddit.collections.SubredditCollections: ...
    @property
    def contributor(self) -> praw.models.reddit.subreddit.ContributorRelationship: ...
    @property
    def emoji(self) -> SubredditEmoji: ...
    @property
    def filters(self) -> praw.models.reddit.subreddit.SubredditFilters: ...
    @property
    def flair(self) -> praw.models.reddit.subreddit.SubredditFlair: ...
    @property
    def mod(self) -> SubredditModeration: ...
    @property
    def moderator(self) -> praw.models.reddit.subreddit.ModeratorRelationship: ...
    @property
    def modmail(self) -> praw.models.reddit.subreddit.Modmail: ...
    @property
    def muted(self) -> praw.models.reddit.subreddit.SubredditRelationship: ...
    @property
    def quaran(self) -> praw.models.reddit.subreddit.SubredditQuarantine: ...
    @property
    def rules(self) -> SubredditRules: ...
    @property
    def stream(self) -> praw.models.reddit.subreddit.SubredditStream: ...
    @property
    def stylesheet(self) -> praw.models.reddit.subreddit.SubredditStylesheet: ...
    @property
    def widgets(self) -> praw.models.SubredditWidgets: ...
    @property
    def wiki(self) -> praw.models.reddit.subreddit.SubredditWiki: ...
    display_name: Optional[str]
    def __init__(self, reddit: praw.Reddit, display_name: Optional[str] = ..., _data: Optional[Dict[str, Any]] = ...) -> None: ...
    def post_requirements(self) -> Dict[str, Union[str, int, bool]]: ...
    def random(self) -> Union['praw.models.Submission', None]: ...
    def search(self, query: str, *, sort: str = ..., syntax: str = ..., time_filter: str = ..., **generator_kwargs: Any) -> Iterator['praw.models.Submission']: ...
    def sticky(self, *, number: int = ...) -> praw.models.Submission: ...
    def submit(self, title: str, *, collection_id: Optional[str] = ..., discussion_type: Optional[str] = ..., draft_id: Optional[str] = ..., flair_id: Optional[str] = ..., flair_text: Optional[str] = ..., inline_media: Optional[Dict[str, 'praw.models.InlineMedia']] = ..., nsfw: bool = ..., resubmit: bool = ..., selftext: Optional[str] = ..., send_replies: bool = ..., spoiler: bool = ..., url: Optional[str] = ...) -> praw.models.Submission: ...
    def submit_gallery(self, title: str, images: List[Dict[str, str]], *, collection_id: Optional[str] = ..., discussion_type: Optional[str] = ..., flair_id: Optional[str] = ..., flair_text: Optional[str] = ..., nsfw: bool = ..., send_replies: bool = ..., spoiler: bool = ...): ...
    def submit_image(self, title: str, image_path: str, *, collection_id: Optional[str] = ..., discussion_type: Optional[str] = ..., flair_id: Optional[str] = ..., flair_text: Optional[str] = ..., nsfw: bool = ..., resubmit: bool = ..., send_replies: bool = ..., spoiler: bool = ..., timeout: int = ..., without_websockets: bool = ...): ...
    def submit_poll(self, title: str, *, collection_id: Optional[str] = ..., discussion_type: Optional[str] = ..., duration: int, flair_id: Optional[str] = ..., flair_text: Optional[str] = ..., nsfw: bool = ..., options: List[str], resubmit: bool = ..., selftext: str, send_replies: bool = ..., spoiler: bool = ...): ...
    def submit_video(self, title: str, video_path: str, *, collection_id: Optional[str] = ..., discussion_type: Optional[str] = ..., flair_id: Optional[str] = ..., flair_text: Optional[str] = ..., nsfw: bool = ..., resubmit: bool = ..., send_replies: bool = ..., spoiler: bool = ..., thumbnail_path: Optional[str] = ..., timeout: int = ..., videogif: bool = ..., without_websockets: bool = ...): ...
    def subscribe(self, *, other_subreddits: Optional[List['praw.models.Subreddit']] = ...): ...
    def traffic(self) -> Dict[str, List[List[int]]]: ...
    def unsubscribe(self, *, other_subreddits: Optional[List['praw.models.Subreddit']] = ...): ...

class SubredditFilters:
    subreddit: Incomplete
    def __init__(self, subreddit: praw.models.Subreddit) -> None: ...
    def __iter__(self) -> Generator['praw.models.Subreddit', None, None]: ...
    def add(self, subreddit: Union['praw.models.Subreddit', str]): ...
    def remove(self, subreddit: Union['praw.models.Subreddit', str]): ...

class SubredditFlair:
    def link_templates(self) -> praw.models.reddit.subreddit.SubredditLinkFlairTemplates: ...
    def templates(self) -> praw.models.reddit.subreddit.SubredditRedditorFlairTemplates: ...
    def __call__(self, redditor: Optional[Union['praw.models.Redditor', str]] = ..., **generator_kwargs: Any) -> Iterator['praw.models.Redditor']: ...
    subreddit: Incomplete
    def __init__(self, subreddit: praw.models.Subreddit) -> None: ...
    def configure(self, *, link_position: str = ..., link_self_assign: bool = ..., position: str = ..., self_assign: bool = ..., **settings: Any): ...
    def delete(self, redditor: Union['praw.models.Redditor', str]): ...
    def delete_all(self) -> List[Dict[str, Union[str, bool, Dict[str, str]]]]: ...
    def set(self, redditor: Union['praw.models.Redditor', str], *, css_class: str = ..., flair_template_id: Optional[str] = ..., text: str = ...): ...
    def update(self, flair_list: Iterator[Union[str, 'praw.models.Redditor', Dict[str, Union[str, 'praw.models.Redditor']]]], *, text: str = ..., css_class: str = ...) -> List[Dict[str, Union[str, bool, Dict[str, str]]]]: ...

class SubredditFlairTemplates:
    @staticmethod
    def flair_type(is_link: bool) -> str: ...
    subreddit: Incomplete
    def __init__(self, subreddit: praw.models.Subreddit) -> None: ...
    def __iter__(self): ...
    def delete(self, template_id: str): ...
    def update(self, template_id: str, *, allowable_content: Optional[str] = ..., background_color: Optional[str] = ..., css_class: Optional[str] = ..., fetch: bool = ..., max_emojis: Optional[int] = ..., mod_only: Optional[bool] = ..., text: Optional[str] = ..., text_color: Optional[str] = ..., text_editable: Optional[bool] = ...): ...

class SubredditRedditorFlairTemplates(SubredditFlairTemplates):
    def __iter__(self) -> Generator[Dict[str, Union[str, int, bool, List[Dict[str, str]]]], None, None]: ...
    def add(self, text: str, *, allowable_content: Optional[str] = ..., background_color: Optional[str] = ..., css_class: str = ..., max_emojis: Optional[int] = ..., mod_only: Optional[bool] = ..., text_color: Optional[str] = ..., text_editable: bool = ...): ...
    def clear(self) -> None: ...

class SubredditLinkFlairTemplates(SubredditFlairTemplates):
    def __iter__(self) -> Generator[Dict[str, Union[str, int, bool, List[Dict[str, str]]]], None, None]: ...
    def add(self, text: str, *, allowable_content: Optional[str] = ..., background_color: Optional[str] = ..., css_class: str = ..., max_emojis: Optional[int] = ..., mod_only: Optional[bool] = ..., text_color: Optional[str] = ..., text_editable: bool = ...): ...
    def clear(self) -> None: ...
    def user_selectable(self) -> Generator[Dict[str, Union[str, bool]], None, None]: ...

class SubredditModeration:
    def notes(self) -> praw.models.SubredditModNotes: ...
    subreddit: Incomplete
    def __init__(self, subreddit: praw.models.Subreddit) -> None: ...
    def accept_invite(self) -> None: ...
    def edited(self, *, only: Optional[str] = ..., **generator_kwargs: Any) -> Iterator[Union['praw.models.Comment', 'praw.models.Submission']]: ...
    def inbox(self, **generator_kwargs: Any) -> Iterator['praw.models.SubredditMessage']: ...
    def log(self, *, action: Optional[str] = ..., mod: Optional[Union['praw.models.Redditor', str]] = ..., **generator_kwargs: Any) -> Iterator['praw.models.ModAction']: ...
    def modqueue(self, *, only: Optional[str] = ..., **generator_kwargs: Any) -> Iterator[Union['praw.models.Submission', 'praw.models.Comment']]: ...
    def stream(self) -> praw.models.reddit.subreddit.SubredditModerationStream: ...
    def removal_reasons(self) -> SubredditRemovalReasons: ...
    def reports(self, *, only: Optional[str] = ..., **generator_kwargs: Any) -> Iterator[Union['praw.models.Submission', 'praw.models.Comment']]: ...
    def settings(self) -> Dict[str, Union[str, int, bool]]: ...
    def spam(self, *, only: Optional[str] = ..., **generator_kwargs: Any) -> Iterator[Union['praw.models.Submission', 'praw.models.Comment']]: ...
    def unmoderated(self, **generator_kwargs: Any) -> Iterator['praw.models.Submission']: ...
    def unread(self, **generator_kwargs: Any) -> Iterator['praw.models.SubredditMessage']: ...
    def update(self, **settings: Union[str, int, bool]) -> Dict[str, Union[str, int, bool]]: ...

class SubredditModerationStream:
    subreddit: Incomplete
    def __init__(self, subreddit: praw.models.Subreddit) -> None: ...
    def edited(self, *, only: Optional[str] = ..., **stream_options: Any) -> Generator[Union['praw.models.Comment', 'praw.models.Submission'], None, None]: ...
    def log(self, *, action: Optional[str] = ..., mod: Optional[Union[str, 'praw.models.Redditor']] = ..., **stream_options: Any) -> Generator['praw.models.ModAction', None, None]: ...
    def modmail_conversations(self, *, other_subreddits: Optional[List['praw.models.Subreddit']] = ..., sort: Optional[str] = ..., state: Optional[str] = ..., **stream_options: Any) -> Generator[ModmailConversation, None, None]: ...
    def modqueue(self, *, only: Optional[str] = ..., **stream_options: Any) -> Generator[Union['praw.models.Comment', 'praw.models.Submission'], None, None]: ...
    def reports(self, *, only: Optional[str] = ..., **stream_options: Any) -> Generator[Union['praw.models.Comment', 'praw.models.Submission'], None, None]: ...
    def spam(self, *, only: Optional[str] = ..., **stream_options: Any) -> Generator[Union['praw.models.Comment', 'praw.models.Submission'], None, None]: ...
    def unmoderated(self, **stream_options: Any) -> Generator['praw.models.Submission', None, None]: ...
    def unread(self, **stream_options: Any) -> Generator['praw.models.SubredditMessage', None, None]: ...

class SubredditQuarantine:
    subreddit: Incomplete
    def __init__(self, subreddit: praw.models.Subreddit) -> None: ...
    def opt_in(self) -> None: ...
    def opt_out(self) -> None: ...

class SubredditRelationship:
    def __call__(self, redditor: Optional[Union[str, 'praw.models.Redditor']] = ..., **generator_kwargs) -> Iterator['praw.models.Redditor']: ...
    relationship: Incomplete
    subreddit: Incomplete
    def __init__(self, subreddit: praw.models.Subreddit, relationship: str) -> None: ...
    def add(self, redditor: Union[str, 'praw.models.Redditor'], **other_settings: Any): ...
    def remove(self, redditor: Union[str, 'praw.models.Redditor']): ...

class ContributorRelationship(SubredditRelationship):
    def leave(self) -> None: ...

class ModeratorRelationship(SubredditRelationship):
    PERMISSIONS: Incomplete
    def __call__(self, redditor: Optional[Union[str, 'praw.models.Redditor']] = ...) -> List['praw.models.Redditor']: ...
    def add(self, redditor: Union[str, 'praw.models.Redditor'], *, permissions: Optional[List[str]] = ..., **other_settings: Any): ...
    def invite(self, redditor: Union[str, 'praw.models.Redditor'], *, permissions: Optional[List[str]] = ..., **other_settings: Any): ...
    def invited(self, *, redditor: Optional[Union[str, 'praw.models.Redditor']] = ..., **generator_kwargs: Any) -> Iterator['praw.models.Redditor']: ...
    def leave(self) -> None: ...
    def remove_invite(self, redditor: Union[str, 'praw.models.Redditor']): ...
    def update(self, redditor: Union[str, 'praw.models.Redditor'], *, permissions: Optional[List[str]] = ...): ...
    def update_invite(self, redditor: Union[str, 'praw.models.Redditor'], *, permissions: Optional[List[str]] = ...): ...

class Modmail:
    def __call__(self, id: Optional[str] = ..., mark_read: bool = ...): ...
    subreddit: Incomplete
    def __init__(self, subreddit: praw.models.Subreddit) -> None: ...
    def bulk_read(self, *, other_subreddits: Optional[List[Union['praw.models.Subreddit', str]]] = ..., state: Optional[str] = ...) -> List[ModmailConversation]: ...
    def conversations(self, *, after: Optional[str] = ..., other_subreddits: Optional[List['praw.models.Subreddit']] = ..., sort: Optional[str] = ..., state: Optional[str] = ..., **generator_kwargs) -> Iterator[ModmailConversation]: ...
    def create(self, *, author_hidden: bool = ..., body: str, recipient: Union[str, 'praw.models.Redditor'], subject: str) -> ModmailConversation: ...
    def subreddits(self) -> Generator['praw.models.Subreddit', None, None]: ...
    def unread_count(self) -> Dict[str, int]: ...

class SubredditStream:
    subreddit: Incomplete
    def __init__(self, subreddit: praw.models.Subreddit) -> None: ...
    def comments(self, **stream_options: Any) -> Generator['praw.models.Comment', None, None]: ...
    def submissions(self, **stream_options: Any) -> Generator['praw.models.Submission', None, None]: ...

class SubredditStylesheet:
    def __call__(self) -> praw.models.Stylesheet: ...
    subreddit: Incomplete
    def __init__(self, subreddit: praw.models.Subreddit) -> None: ...
    def delete_banner(self) -> None: ...
    def delete_banner_additional_image(self) -> None: ...
    def delete_banner_hover_image(self) -> None: ...
    def delete_header(self) -> None: ...
    def delete_image(self, name: str): ...
    def delete_mobile_header(self) -> None: ...
    def delete_mobile_icon(self) -> None: ...
    def update(self, stylesheet: str, *, reason: Optional[str] = ...): ...
    def upload(self, *, image_path: str, name: str) -> Dict[str, str]: ...
    def upload_banner(self, image_path: str): ...
    def upload_banner_additional_image(self, image_path: str, *, align: Optional[str] = ...): ...
    def upload_banner_hover_image(self, image_path: str): ...
    def upload_header(self, image_path: str) -> Dict[str, str]: ...
    def upload_mobile_header(self, image_path: str) -> Dict[str, str]: ...
    def upload_mobile_icon(self, image_path: str) -> Dict[str, str]: ...

class SubredditWiki:
    def __getitem__(self, page_name: str) -> WikiPage: ...
    banned: Incomplete
    contributor: Incomplete
    subreddit: Incomplete
    def __init__(self, subreddit: praw.models.Subreddit) -> None: ...
    def __iter__(self) -> Generator[WikiPage, None, None]: ...
    def create(self, *, content: str, name: str, reason: Optional[str] = ..., **other_settings: Any): ...
    def revisions(self, **generator_kwargs: Any) -> Generator[Dict[str, Optional[Union['praw.models.Redditor', WikiPage, str, int, bool]]], None, None]: ...
