import praw
from ..exceptions import DuplicateReplaceException as DuplicateReplaceException
from .reddit.more import MoreComments as MoreComments
from typing import List, Optional, Union

class CommentForest:
    def __getitem__(self, index: int): ...
    def __init__(self, submission: praw.models.Submission, comments: Optional[List['praw.models.Comment']] = ...) -> None: ...
    def __len__(self) -> int: ...
    def list(self) -> List[Union['praw.models.Comment', 'praw.models.MoreComments']]: ...
    def replace_more(self, *, limit: int = ..., threshold: int = ...) -> List['praw.models.MoreComments']: ...
